ARG BASE=nvidia/cuda:12.6.3-base-ubuntu24.04
FROM ${BASE} AS base

SHELL ["/bin/bash", "-c"]

ENV DEBIAN_FRONTEND=noninteractive

# Create a non-root user if necessary

# I assume there is already a user created in the base image
ARG USERNAME=ubuntu
ENV USERNAME=$USERNAME
# ARG USER_UID=1000
# ARG USER_GID=$USER_UID

# RUN groupadd --gid $USER_GID $USERNAME \
#   && useradd -m \
#   -s /bin/bash \
#   -G sudo \
#   --uid $USER_UID \
#   --gid $USER_GID \
#   $USERNAME \
#   # Add sudo support for the non-root user
#   && apt-get update \
#   && apt-get install -y sudo \
#   && echo "$USERNAME ALL=\(root\) NOPASSWD:ALL" > /etc/sudoers.d/$USERNAME\
#   && chmod 0440 /etc/sudoers.d/$USERNAME \
#   && rm -rf /var/lib/apt/lists/*

RUN apt-get update \
  && apt-get install -y sudo \
  && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
  && chmod 0440 /etc/sudoers.d/$USERNAME \
  && rm -rf /var/lib/apt/lists/*

# Install OS dependencies:
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y --no-install-recommends \
    gcc g++ make libc-dev curl \
    python3 python3-dev python3-pip python3-venv python3-wheel \
    espeak-ng libsndfile1-dev \
    && rm -rf /var/lib/apt/lists/*

USER $USERNAME
ENV HOME=/home/$USERNAME

# Install Rust compiler (to build sudachipy for Mac)
RUN curl --proto '=https' --tlsv1.2 -sSf "https://sh.rustup.rs" | sh -s -- -y
ENV CARGO_HOME=/home/${USERNAME}/.cargo
ENV PATH="${CARGO_HOME}/bin:${PATH}"

# Create a virtual environment:
ENV VIRTUAL_ENV=${HOME}/opt/.venv
RUN python3 -m venv ${VIRTUAL_ENV}

# Activate the virtual environment:
ENV PATH="${VIRTUAL_ENV}/bin:$PATH"

# Install Major Python Dependencies:
RUN python -m pip install --upgrade pip \
    && python -m pip install --upgrade setuptools wheel \
    && python -m pip install llvmlite --ignore-installed \
    && python -m pip install torch torchaudio --extra-index-url https://download.pytorch.org/whl/cu118

COPY --chown=${USERNAME}:${USERNAME} requirements.txt ${HOME}/opt/requirements.txt

# Install core dependencies of the TTS package:
RUN python -m pip install -Ur ${HOME}/opt/requirements.txt

ENV DEBIAN_FRONTEND=

FROM base AS app

ENV DEBIAN_FRONTEND=noninteractive

# Create the workspace directory:
ARG WORKSPACE=/app
ENV WORKSPACE=$WORKSPACE  
WORKDIR $WORKSPACE

# Copy TTS repository contents:
COPY --chown=${USERNAME}:${USERNAME} . $WORKSPACE

RUN python -m pip install -e .[all,dev]

ENTRYPOINT ["/bin/bash", "-c", "exec \"$@\"", "--"]
CMD ["tts-server", "--list_models"]

ENV DEBIAN_FRONTEND=

FROM base AS dev

ENV DEBIAN_FRONTEND=noninteractive

RUN sudo apt-get update && sudo apt-get install -y --no-install-recommends \
    git \
    && sudo rm -rf /var/lib/apt/lists/*

# Create the workspace directory:
ARG WORKSPACE=/app
ENV WORKSPACE=$WORKSPACE  
WORKDIR $WORKSPACE

# Copy TTS repository contents:
COPY --from=app ${VIRTUAL_ENV} ${VIRTUAL_ENV}
COPY --from=app ${CARGO_HOME} ${CARGO_HOME}

ENTRYPOINT ["/bin/bash", "-c", "exec \"$@\"", "--"]
CMD ["sleep", "infinity"]

ENV DEBIAN_FRONTEND=
